name: Daily LinkedIn Post

on:
  schedule:
    - cron: '37 8 * * *'
  workflow_dispatch:

jobs:
  post:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run agent
        env:
          GROQ_API_KEY: ${{ secrets.GROQ_API_KEY }}
          BUFFER_API_KEY: ${{ secrets.BUFFER_API_KEY }}
          CHANNEL_ID: ${{ secrets.CHANNEL_ID }}
          ORGANIZATION_ID: ${{ secrets.ORGANIZATION_ID }}
        run: python main.py

      - name: Save post history
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git remote set-url origin https://github.com/SaniaKhizar/daily-linkedIn-post-agent.git
          git add post_history.json
          git commit -m "update post history" || echo "No changes to commit"
          git push